<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# " lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>unittest.mock small gotcha - a humbling tale of failure | Coding Diet</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta content="#5670d4" name="theme-color">
<link rel="alternate" type="application/rss+xml" title="RSS" href="../../rss.xml">
<link rel="canonical" href="https://allanderek.github.io/posts/unittestmock-small-gotcha/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Allan Clark">
<link rel="prev" href="../flask-and-pytest-coverage/" title="Flask and Pytest coverage" type="text/html">
<meta property="og:site_name" content="Coding Diet">
<meta property="og:title" content="unittest.mock small gotcha - a humbling tale of failure">
<meta property="og:url" content="https://allanderek.github.io/posts/unittestmock-small-gotcha/">
<meta property="og:description" content="Developing a small web application I recently had reason to upgrade from Python 3.4 to Python 3.6. The reason for the upgrade was regarding ordering of keyword arguments and not related to the bug in ">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2017-02-25T12:36:24Z">
<meta property="article:tag" content="3.4">
<meta property="article:tag" content="3.5">
<meta property="article:tag" content="3.6">
<meta property="article:tag" content="mock">
<meta property="article:tag" content="python">
<meta property="article:tag" content="standard library">
<meta property="article:tag" content="testing">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://allanderek.github.io/">

                <span id="blog-title">Coding Diet</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>
                </li>
<li>
<a href="../../rss.xml">RSS feed</a>
                </li>
<li>
<a href="../../stories/curriculum-vitae/">CV</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li>
    <a href="index.md" id="sourcelink">Source</a>
    </li>

                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">unittest.mock small gotcha - a humbling tale of failure</a></h1>

        <div class="metadata">
            <p class="byline author vcard"><span class="byline-name fn">
                    Allan Clark
            </span></p>
            <p class="dateline"><a href="." rel="bookmark"><time class="published dt-published" datetime="2017-02-25T12:36:24Z" itemprop="datePublished" title="2017-02-25 12:36">2017-02-25 12:36</time></a></p>
                <p class="commentline">
        
    <a href="#disqus_thread" data-disqus-identifier="cache/posts/unittestmock-small-gotcha.html">Comments</a>


            
        </p>
<p class="sourceline"><a href="index.md" id="sourcelink">Source</a></p>

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <div>
<p>Developing a small web application I recently had reason to upgrade from Python 3.4 to Python 3.6. The reason for the upgrade was regarding ordering of keyword arguments and not related to the bug in my test code that I then found. I should have been more careful writing my test code in the first place, so I am writing this down as some penance for not testing my tests robustly enough.</p>
<h3>A Simple example program</h3>
<p>So here I have a version of the problem reduced down to the minimum required to demonstrate the issue:</p>
<pre class="code literal-block"><span></span><span class="kn">import</span> <span class="nn">unittest.mock</span> <span class="kn">as</span> <span class="nn">mock</span>

<span class="k">class</span> <span class="nc">MyClass</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">pass</span>
    <span class="k">def</span> <span class="nf">my_method</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">pass</span>

<span class="k">if</span> <span class="n">__name__</span> <span class="o">==</span> <span class="s1">'__main__'</span><span class="p">:</span>
    <span class="k">with</span> <span class="n">mock</span><span class="o">.</span><span class="n">patch</span><span class="p">(</span><span class="s1">'__main__.MyClass'</span><span class="p">)</span> <span class="k">as</span> <span class="n">MockMyClass</span><span class="p">:</span>
        <span class="n">MyClass</span><span class="p">()</span><span class="o">.</span><span class="n">my_method</span><span class="p">()</span>
        <span class="n">MockMyClass</span><span class="o">.</span><span class="n">my_method</span><span class="o">.</span><span class="n">assert_called_once</span><span class="p">()</span>
</pre>


<p>Of course in reality the line <code>MyClass().my_method()</code> was some test code that indirectly caused the target method to be called.</p>
<h4>Output in Python 3.4</h4>
<pre class="code literal-block"><span></span>$ python3.4 mock_example.py
$
</pre>


<p>No output, leading me to believe my assertions passed, so I was happy that my code and my tests were working. As it turned out, my code was fine but my test was faulty. Here's the output in two later versions of Python of the exact same program given above.</p>
<h4>Output in Python 3.5</h4>
<pre class="code literal-block"><span></span>$ python3.5 mock_example.py
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"mock_example.py"</span>, line 12, in &lt;module&gt;
    MockMyClass.my_method.assert_called_once<span class="o">()</span>
  File <span class="s2">"/usr/lib/python3.5/unittest/mock.py"</span>, line 583, in __getattr__
    raise AttributeError<span class="o">(</span>name<span class="o">)</span>
AttributeError: assert_called_once
</pre>


<p>Assertion error, test failing.</p>
<h4>Output in Python 3.6</h4>
<pre class="code literal-block"><span></span>$ python3.6 mock_example.py
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"mock_example.py"</span>, line 12, in &lt;module&gt;
    MockMyClass.my_method.assert_called_once<span class="o">()</span>
  File <span class="s2">"/usr/lib/python3.6/unittest/mock.py"</span>, line 795, in assert_called_once
    raise AssertionError<span class="o">(</span>msg<span class="o">)</span>
AssertionError: Expected <span class="s1">'my_method'</span> to have been called once. Called <span class="m">0</span> times.
</pre>


<p>Test also failing with a different error message. Anyone who is (pretty) familiar with the <code>unittest.mock</code> standard library module will know <code>assert_called_once</code> was introduced in version 3.6, which is my version 3.5 is failing with an attribute error.</p>
<h3>My test was wrong</h3>
<p>The problem was, my original test was not testing anything at all. The 3.4 version of the <code>unittest.mock</code> standard library module did not have a <code>assert_called_once</code>. The mock, just allows you to call any method on it, to see this you can try changing the line:</p>
<pre class="code literal-block"><span></span>        <span class="n">MockMyClass</span><span class="o">.</span><span class="n">my_method</span><span class="o">.</span><span class="n">assert_called_once</span><span class="p">()</span>
</pre>


<p>to</p>
<pre class="code literal-block"><span></span>        <span class="n">MockMyClass</span><span class="o">.</span><span class="n">my_method</span><span class="o">.</span><span class="n">blahblah</span><span class="p">()</span>
</pre>


<p>With <code>python3.4</code>, <code>python3.5</code>, and <code>python3.6</code> this yields no error. So in the original program you can avoid the calling <code>MyClass.my_method</code> at all:</p>
<pre class="code literal-block"><span></span><span class="k">if</span> <span class="n">__name__</span> <span class="o">==</span> <span class="s1">'__main__'</span><span class="p">:</span>
    <span class="k">with</span> <span class="n">mock</span><span class="o">.</span><span class="n">patch</span><span class="p">(</span><span class="s1">'__main__.MyClass'</span><span class="p">)</span> <span class="k">as</span> <span class="n">MockMyClass</span><span class="p">:</span>
        <span class="c1"># Missing call to `MyClass().my_method()`</span>
        <span class="n">MockMyClass</span><span class="o">.</span><span class="n">my_method</span><span class="o">.</span><span class="n">assert_called_once</span><span class="p">()</span> <span class="c1"># In 3.4 this still passes.</span>
</pre>


<p>This does not change the (original) results, <code>python3.4</code> still raises <strong>no error</strong>, whereas <code>python3.5</code> and <code>python3.6</code> are raising the original errors.</p>
<p>So although my code turned out to be correct (at least in as much as the desired method was called), had it been faulty (or changed to be faulty) my test would not have complained.</p>
<h3>The Actual Problem</h3>
<p>My mock was wrong. I should instead have been patching the actual method within the class, like so:</p>
<pre class="code literal-block"><span></span><span class="k">if</span> <span class="n">__name__</span> <span class="o">==</span> <span class="s1">'__main__'</span><span class="p">:</span>
    <span class="k">with</span> <span class="n">mock</span><span class="o">.</span><span class="n">patch</span><span class="p">(</span><span class="s1">'__main__.MyClass.my_method'</span><span class="p">)</span> <span class="k">as</span> <span class="n">mock_my_method</span><span class="p">:</span>
        <span class="n">MyClass</span><span class="p">()</span><span class="o">.</span><span class="n">my_method</span><span class="p">()</span>
        <span class="n">mock_my_method</span><span class="o">.</span><span class="n">assert_called_once</span><span class="p">()</span>
</pre>


<p>Now if we try this in all version 3.4, 3.5, and 3.6 of python we get:</p>
<pre class="code literal-block"><span></span>$ python3.4 mock_example.py 
$ python3.5 mock_example.py 
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"mock_example.py"</span>, line 12, in &lt;module&gt;
    mock_my_method.assert_called_once<span class="o">()</span>
  File <span class="s2">"/usr/lib/python3.5/unittest/mock.py"</span>, line 583, in __getattr__
    raise AttributeError<span class="o">(</span>name<span class="o">)</span>
AttributeError: assert_called_once
$ python3.6 mock_example.py 
$ 
</pre>


<p>So Python 3.4 and 3.6 pass as we expect. But Python3.5 gives an error stating that there is no <code>assert_called_once</code> method on the mock object, which is true since that method was not added until version 3.6. This is arguably what Python3.4 should have done.</p>
<p>It remains to check that the updated test fails in Python3.6, so we comment out the call to <code>MyClass().my_method</code>:</p>
<pre class="code literal-block"><span></span>$ python3.6 mock_example.py 
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"mock_example.py"</span>, line 12, in &lt;module&gt;
    mock_my_method.assert_called_once<span class="o">()</span>
  File <span class="s2">"/usr/lib/python3.6/unittest/mock.py"</span>, line 795, in assert_called_once
    raise AssertionError<span class="o">(</span>msg<span class="o">)</span>
AssertionError: Expected <span class="s1">'my_method'</span> to have been called once. Called <span class="m">0</span> times.
</pre>


<p>This is the test I <strong>should</strong> have performed with my original test. Had I done this I would have seen that the test passed in Python3.4 regardless of whether the method in question was actually called or not.</p>
<p>So now my test works in <code>python3.6</code>, fails in <code>python3.5</code> because I'm using the method <code>assert_called_once</code> which was introduced in <code>python3.6</code>. Unfortunately it incorrectly passes in <code>python3.4</code>. So if I want my code to work properly for python versions earlier than 3.6, then I can essentially implement <code>assert_called_once()</code> with <code>assert len(mock_my_method.mock_calls) == 1</code>. If we do this then my test passes in all three version of python and fails in all three if we comment out the call <code>MyClass().my_method()</code>.</p>
<h3>Conclusions</h3>
<p>I made an error in writing my original test, but my real sin was that I was a bit lazy in that I did not make sure that my tests would fail, when the code was incorrect. In this instance there was no problem with the code only the test, but that was luck. So for me, this served as a reminder to check that your tests can fail. It may be that mutation testing would have caught this error.</p>
</div>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/34/" rel="tag">3.4</a></li>
            <li><a class="tag p-category" href="../../categories/35/" rel="tag">3.5</a></li>
            <li><a class="tag p-category" href="../../categories/36/" rel="tag">3.6</a></li>
            <li><a class="tag p-category" href="../../categories/mock/" rel="tag">mock</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/standard-library/" rel="tag">standard library</a></li>
            <li><a class="tag p-category" href="../../categories/testing/" rel="tag">testing</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../flask-and-pytest-coverage/" rel="prev" title="Flask and Pytest coverage">Previous post</a>
            </li>
        </ul></nav></aside><section class="comments hidden-print"><h2>Comments</h2>
        
        
        <div id="disqus_thread"></div>
        <script>
        var disqus_shortname ="allanderek",
            disqus_url="https://allanderek.github.io/posts/unittestmock-small-gotcha/",
        disqus_title="unittest.mock small gotcha - a humbling tale of failure",
        disqus_identifier="cache/posts/unittestmock-small-gotcha.html",
        disqus_config = function () {
            this.language = "en";
        };
        (function() {
            var dsq = document.createElement('script'); dsq.async = true;
            dsq.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script><noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
</noscript>
    <a href="https://disqus.com" class="dsq-brlink" rel="nofollow">Comments powered by <span class="logo-disqus">Disqus</span></a>


        </section></article><script>var disqus_shortname="allanderek";(function(){var a=document.createElement("script");a.async=true;a.src="https://"+disqus_shortname+".disqus.com/count.js";(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(a)}());</script>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2017         <a href="mailto:allan.clark@gmail.com">Allan Clark</a> - Powered by         <a href="https://getnikola.com" rel="nofollow">Nikola</a>         
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><script>$('a.image-reference:not(.islink) img:not(.islink)').parent().colorbox({rel:"gal",maxWidth:"100%",maxHeight:"100%",scalePhotos:true});</script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates -->
</body>
</html>
